# Generated by Django 2.2 on 2020-03-30 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200319_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(default='No', max_length=3)),
                ('friends', models.CharField(default='No', max_length=3)),
                ('freq_accp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_accep', to=settings.AUTH_USER_MODEL)),
                ('freq_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
