# Generated by Django 2.2 on 2020-04-14 09:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_avatar_profile.jpg', upload_to=users.models.profile_img_directory),
        ),
    ]
