# Generated by Django 2.2 on 2020-04-26 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usercover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercover',
            name='cover_photo',
            field=models.ImageField(upload_to=users.models.cover_photo_directory),
        ),
        migrations.AlterField(
            model_name='usercover',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
