# Generated by Django 2.2 on 2020-04-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_comments_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feed',
            name='post_info',
            field=models.CharField(default='', max_length=255),
        ),
    ]
