# Generated by Django 2.2 on 2020-04-20 19:53

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20200420_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, upload_to=feed.models.feed_data_directory),
        ),
    ]
