# Generated by Django 2.2 on 2020-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20200420_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='post_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
