# Generated by Django 2.2 on 2020-05-01 13:15

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20200421_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=feed.models.feed_data_directory),
        ),
    ]
