# Generated by Django 2.2 on 2020-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_relatedcommentslikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikes',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
